apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
spec:
  tracing:
    samplingRate: "1"
    expandParams: true
    includeBody: true
    zipkin:
      endpointAddress: "http://localhost:9412/api/v2/spans"
  metrics:
    enabled: true
  